//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatryoshCoin.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calculation
    {
        public int CompilationID { get; set; }
        public string Result { get; set; }
        public int AccountID { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
